FROM ubuntu

RUN apt-get update

CMD ["echo", "#sun #Suva #SãoTomé #Gitega #australia #spain #carribean #Ottawa #adria #Wien #Castries #travelphotography #diving #portugal #beach #Kairo #Kapstadt #snorkel #greece #Paramaribo #Monrovia #architecture #Belmopan #scubadiving #city #italy #travel #europe #nature #Reykjavík "]

CMD ["echo", "#travel #Ankara #snorkel #scubadiving #Baku #Monrovia #greece #italy #europe #portugal #beach #Nassau #nature #australia #carribean #PortLouis #spain #Algier #architecture #city #sun #PortVila #travelphotography #Kinshasa #Manila #diving #Reykjavík #Dublin #adria #Apia "]

CMD ["echo", "#Wellington #Duschanbe #nature #portugal #Dodoma #italy #snorkel #scubadiving #Kuwait #carribean #beach #Banjul #architecture #Reykjavík #europe #Sanaa #diving #Ottawa #adria #australia #travelphotography #travel #Bukarest #sun #city #Dakar #spain #Basseterre #greece #Daressalam "]

CMD ["echo", "#portugal #AndorralaVella #diving #greece #nature #travelphotography #scubadiving #Reykjavík #architecture #AbuDhabi #beach #Palikir #Vaduz #Duschanbe #snorkel #Nikosia #Mogadischu #travel #italy #Yaounde #carribean #Stockholm #Vatikanstadt #Lissabon #australia #sun #europe #adria #city #spain "]

CMD ["echo", "#city #greece #Kapstadt #nature #carribean #adria #australia #Dakar #beach #scubadiving #europe #Amman #Ulaanbaatar #Warschau #travel #Paramaribo #spain #Victoria #architecture #Belmopan #travelphotography #italy #diving #portugal #snorkel #Port-au-Prince #Brazzaville #Reykjavík #Sofia #sun "]

CMD ["echo", "#Dschibuti #australia #Vientiane #Conakry #Manila #italy #spain #nature #Riad #architecture #greece #BuenosAires #Bukarest #Maskat #Khartum #diving #adria #Reykjavík #sun #europe #Athen #travel #snorkel #scubadiving #city #Sarajevo #carribean #beach #portugal #travelphotography "]

CMD ["echo", "#portugal #scubadiving #Pjöngjang #Wien #greece #Reykjavík #Luxemburg #architecture #travelphotography #europe #nature #Dublin #australia #Khartum #Podgorica #sun #Aden #Neu-Delhi #Monaco #spain #italy #adria #Malabo #travel #diving #beach #Riga #carribean #city #snorkel "]

CMD ["echo", "#travel #snorkel #beach #city #nature #spain #Kingston #scubadiving #australia #diving #travelphotography #SanJose #adria #carribean #Ngerulmud #Athen #italy #Abidjan #Moskau #Reykjavík #Georgetown #SantoDomingo #Luxemburg #europe #architecture #greece #portugal #Asmara #sun #Ouagadougou "]

CMD ["echo", "#Neu-Delhi #Maputo #beach #Ottawa #Kairo #portugal #Kingston #Kopenhagen #scubadiving #Paramaribo #europe #sun #Damaskus #greece #city #carribean #italy #nature #Rom #australia #architecture #snorkel #adria #diving #Gaborone #Manama #travelphotography #Reykjavík #spain #travel "]

CMD ["echo", "#snorkel #architecture #diving #sun #travelphotography #europe #italy #Conakry #spain #scubadiving #greece #Reykjavík #Algier #Podgorica #Suva #Monrovia #Maskat #Athen #nature #city #Paris #carribean #adria #Kathmandu #travel #australia #Islamabad #Bischkek #beach #portugal "]

CMD ["echo", ""]

